### ISSUE TITLE
FEATURE: Add citation

### ISSUE THREAD

**Issue by norwd** [norwd/pword#110]
### Is your feature request related to a problem?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

### What solutions have you considered?

`CITATION.cff`

```yaml
cff-version: 1.2.0
type: software
license: Unlicense
title: pword
abstract: 'A small, command line password generator.'
message: If you use this software, please cite it using these metadata.
url: 'https://github.com/norwd/pword#readme'
repository-code: 'https://github.com/norwd/pword'
repository-artifact: 'https://gobinaries.com/norwd/pword@latest'
authors:
  - family-names: Meyer-Norwood
    given-names: Yuri
keywords:
  - go
  - golang
  - passwords
  - password-generator
```

### What alternatives have you considered?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
